### ISSUE TITLE
RegAsm Installation Issue

### ISSUE THREAD

**Issue by EpicnessTwo** [as08/ClassicASP.Bcrypt#1]
I'm getting a strange error when trying to install this on Windows Server 2016.

I've installed the recommended version of .Net but nothing has changed. Managed to get this installed just fine on other systems, just not this version of Windows Server...

```
C:\Windows\Microsoft.NET\Framework64\v4.0.30319>RegAsm ClassicASP.Bcrypt.dll /tlb /codebase
Microsoft .NET Framework Assembly Registration Utility version 4.6.1586.0
for Microsoft .NET Framework version 4.6.1586.0
Copyright (C) Microsoft Corporation.  All rights reserved.

RegAsm : error RA0000 : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

Any ideas?

**Comment by EpicnessTwo** [comment]
Solved! It seems that Windows Server 2016 doesn't ship with `netstandard.dll` which was causing the issue. Compared this to a newer server and a few others of the same OS version which confirmed this answer.

**Comment by leighmetzroth** [comment]
For those that come across this like I did, but find that it was solved but with no details on how to solve it for themselves...  all you need to do is install .net Framework 4.7.1 or later, and you will then have the `netstandard.dll`.
